# Generated by Django 2.0.6 on 2021-08-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('pk_exam', models.AutoField(primary_key=True, serialize=False)),
                ('alumno', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=100, null=True)),
                ('observaciones', models.TextField(null=True)),
            ],
        ),
    ]
